name: Postman Collection Runner

on:
  push:
    branches:
      - main

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Newman
        run: npm install -g newman

      - name: Set Collection Variables
        run: |
          echo "{
            \"id\": \"45327923-4ff1-4d95-8f4f-8683bbdcfffc\",
            \"values\": [
              {
                \"key\": \"variable_key\",
                \"value\": \"${{ secrets.GITHUB_ENV_VARIABLE }}\",
                \"enabled\": true
              }
              // Add more variables if needed
            ]
          }" > collection_variables.json

      - name: Run Postman Collection
        id: newman
        run: newman run postman_collection.json --envVar collection_variables.json --reporters cli,junit --reporter-junit-export postman-report.xml

      - name: Parse Newman Results
        id: parse-results
        run: |
          echo "FAILED_TESTS=$(grep -oP '(?<=<failure>).*(?=<\/failure>)' postman-report.xml | wc -l)" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$(grep -oP '(?<=tests\=\"\d+\").*(?=\")' postman-report.xml | grep -oP '\d+')" >> $GITHUB_ENV

      - name: Check Test Results
        run: |
          failed_tests=$FAILED_TESTS
          total_tests=$TOTAL_TESTS
          if [[ "$failed_tests" -gt 0 ]]; then
            echo "Postman tests failed: $failed_tests/$total_tests"
            exit 1
          else
            echo "All Postman tests passed: $total_tests/$total_tests"
          fi
